### ISSUE TITLE
Wiremock download through proxy server

### ISSUE THREAD

**Issue by D0rmouse** [erwinheitzman/wdio-wiremock-service#14]
On my Windows 10 machine the download of Wiremock fails (see below). 
When going directly to the maven URL, or using curl to download wiremock in onPrepare manually, the download succeeds. 
This leads me to believe it's a problem in the wdio-wiremock-service. Maybe proxy settings should be added?

```
Downloading WireMock standalone from Maven Central...
  https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.2/wiremock-standalone-2.27.2.jar
...
2021-01-09T17:57:51.852Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Downloading WireMock jar from Maven Central failed: Error: connect ETIMEDOUT 151.101.16.209:443

    at WiremockLauncher.<anonymous> (D:\dev\projects\beheer-web\node_modules\wdio-wiremock-service\lib\launcher.js:29:27)
    at Generator.throw (<anonymous>)
    at rejected (D:\dev\projects\beheer-web\node_modules\wdio-wiremock-service\lib\launcher.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Continue...
```

**Comment by erwinheitzman** [comment]
Hi @D0rmouse thank you for reporting this issue.

Did you use the exact same url to download? Also, are you behind a proxy?

If you are behind a proxy I would have to look into how I can support this. Do you already have some proxy settings setup for WebdriverIO for example which I would reuse in the service?

**Comment by D0rmouse** [comment]
Used the exact same url in different ways and the artifact is downloaded.
We did it manually in onPrepare (before we knew about this service) using curl and that works too. 

Maybe the system proxy can be read and used? Or another client, like curl?
Don't have proxy settings for WebdriverIO available at this point unfortunately.

**Comment by D0rmouse** [comment]
Maybe [this](https://stackoverflow.com/questions/34078995/how-can-i-use-an-https-proxy-with-node-js-https-request-client) can help? 

It's recommended to use `request` instead of `https` as it has proxy options.

**Comment by erwinheitzman** [comment]
That's a great link and though he says that the request package is recommended, the creator of the package says it's deprecated due to nodejs having evolved, so I'll look into adding support for this soon. I'll see wether I can get it up and running tomorrow as it's already really late over here in the Netherlands.

**Comment by D0rmouse** [comment]
Haha, inderdaad!

**Comment by erwinheitzman** [comment]
Haha, nice! :D

I have been looking into this but I have no idea how I can test this locally to be honest.
I'd love to be able to test it and then cover it with unit tests.

Do you happen to have any knowledge on how something like this can be tested locally? Like setting up a local proxy with a small Express app perhaps.

From what I have seen the following code should work but if I can't test it I can't really tell :(
```js
	private static _downloadWithProxy(url: string): Promise<IncomingMessage> {
		return new Promise((resolve, reject) => {

			const proxyparts = URL.parse(process.env.https_proxy as string);
			const urlParts = URL.parse(url);

			http.request({
				host: proxyparts.hostname,
				port: proxyparts.port,
				method: 'CONNECT',
				path: urlParts.hostname + ':443'
			}).on('connect', (res, socket, head) => {
				const req = https.get({
					host: urlParts.hostname as string,
					socket: socket,
					path: urlParts.path as string,
					agent: false
				}, (res) => {
					if (res.statusCode !== 200) {
						return reject(new Error('statusCode=' + res.statusCode));
					}

					return resolve(res);
				});

				req.on('error', (err) => {
					reject(err);
				});

				req.end();
			}).end();
		});
	}
```

**Comment by D0rmouse** [comment]
To me it seems easiest to mock the proxy server and assert in the test that the mock is hit with the correct parameters.

In the scenario the proxy shouldn't be contacted, you can assert the mock server isn't hit.

**Comment by erwinheitzman** [comment]
Well I meant more of a manual test so that I can verify that this setup actually works 😄

**Comment by D0rmouse** [comment]
You could install a proxy server on your machine, or - if I have a version containing the change - I could test it using the corporate proxy.

**Comment by erwinheitzman** [comment]
@D0rmouse after some reading it seems like doing the following: https://gist.github.com/alienlebarge/10260853

Should actually be enough to get it working already.

Official doc reference: https://docs.npmjs.com/cli/v6/using-npm/config#https-proxy

As you can see the native request lib (http and https modules) will respect those settings so I am wondering if this is something you have not setup, tried before you created this issue.

It's a pity that I'm not working behind a proxy server atm in order to test this myself but I'd love to hear if configuring nodejs to use the proxy settings, fixes the issue for you.

**Comment by D0rmouse** [comment]
I have environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY set, but it seems they're not used by default by node.js' http module.

**Comment by D0rmouse** [comment]
Output of a run using wdio-wiremock-service:

```
http_proxy: http://proxy.xxxxx.nl:8080
https_proxy: http://proxy.xxxxx.nl:8080
Downloading WireMock standalone from Maven Central...
  https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.2/wiremock-standalone-2.27.2.jar
Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2021-01-12T09:43:41.159Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Downloading WireMock jar from Maven Central failed: Error: connect ETIMEDOUT 151.101.36.209:443
```

NPM config:
```
>npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.6 node/v12.18.3 win32 x64"

; project config D:\dev\projects\xxxxx\.npmrc
https-proxy = "http://proxy.xxxxx.nl:8080/"
noproxy = "xxxxx,localhost"
proxy = "http://proxy.xxxxx.nl:8080/"
registry = "https://registry.npmjs.org/"
strict-ssl = false

; userconfig C:\Users\xxxxx\.npmrc
https-proxy = "http://proxy.xxxxx.nl:8080/"
proxy = "http://proxy.xxxxx.nl:8080/"
strict-ssl = false

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\dev\projects\xxxxx
; HOME = C:\Users\xxxxx
; "npm config ls -l" to show all defaults.
```

Configuration should be good as far as I can tell. 

I've worked around it now by changing the mavenBaseUrl to our corporate Nexus server:
```
services: [
    'chromedriver',
    [
        'wiremock',
        {
            mavenBaseUrl: 'https://xxxxx.xxxxx.nl:8443/repository/central',
            rootDir: __dirname.concat('/wiremock'),
            args: [ '--verbose', '--global-response-templating', '--local-response-templating' ]
        }
    ]
]
```

**Comment by D0rmouse** [comment]
After some more digging I found through [this comment](https://gist.github.com/alienlebarge/10260853#gistcomment-2898344) that nodejs doesn't use environment variables by default. 
Using `global-agent` I was able to download the artifact from the public maven repository:
```
process.env.GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE='';
require('global-agent').bootstrap();
```
Thanks for the help :) I'm closing this issue.
