### ISSUE TITLE
Wiremock logging not present on Windows machine

### ISSUE THREAD

**Issue by D0rmouse** [erwinheitzman/wdio-wiremock-service#15]
When using the service on a Windows 10 machine, no logging from Wiremock is present using the stdio inherit or pipe settings.

On Linux machines the logging is present.

**Comment by erwinheitzman** [comment]
Nice find, will have to check why this could be the case 🙂

**Comment by erwinheitzman** [comment]
@D0rmouse before I start looking into this, what are you using?

Git bash, powershell, command line, something else?

**Comment by D0rmouse** [comment]
@erwinheitzman Using a cmd.exe

**Comment by D0rmouse** [comment]
@erwinheitzman I mean the output of wiremock itself, which looks like below:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 /$$      /$$ /$$                     /$$      /$$                     /$$
| $$  /$ | $$|__/                    | $$$    /$$$                    | $$
| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/
| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$
| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/

port:                         8080
enable-browser-proxying:      false
disable-banner:               false
no-request-journal:           false
verbose:                      false

```
I solved it in our manual start of wiremock by doing this:
```
wiremock.stderr.pipe(process.stderr);
wiremock.stdout.pipe(process.stdout);
```

**Comment by erwinheitzman** [comment]
At first I could not get that working but I have found the reason that was causing the issue.

At one point I had a `silent` flag that could be set in order not to log the output but I had changed it so that you can set the stdio options yourself. However when looking back I feel that it makes more sense to have a silent flag that can be passed or left out and removing the option to manually set the stdio options.

What do you think about this?

**Comment by D0rmouse** [comment]
Sounds like a good option :) 

Alternative would be to expose the wiremock spawn reference, but maybe it's not a good idea to expose an internal of the plugin to the client...

**Comment by erwinheitzman** [comment]
@D0rmouse #16 should fix the issue, thank you for creating the issues. Much appreciated as I strive to deliver high quailty.

**Comment by D0rmouse** [comment]
Nice! Thanks for the quick replies and help :) 

When the new version is published, I'll check it out and let you know.

**Comment by erwinheitzman** [comment]
A new version has been published 🎉

**Comment by D0rmouse** [comment]
The logging is there, but at the end of the run the process can't be terminated:
```
2021-01-13T10:09:33.332Z ERROR @wdio/cli:utils: A service failed in the 'onComplete' hook
TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: -35108
    at convertToValidSignal (internal/util.js:251:9)
    at ChildProcess.kill (internal/child_process.js:476:5)
    at WiremockLauncher.<anonymous> (D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:59:77)
    at Generator.next (<anonymous>)
    at D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:4:12)
    at WiremockLauncher.stopProcess (D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:57:16)
    at WiremockLauncher.<anonymous> (D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:51:28)
    at Generator.next (<anonymous>)
    at D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:4:12)
    at WiremockLauncher.onComplete (D:\dev\projects\xxxxx\node_modules\wdio-wiremock-service\lib\launcher.js:49:16)
    at D:\dev\projects\xxxxx\node_modules\@wdio\cli\build\utils.js:25:40
    at Array.map (<anonymous>)
```

**Comment by erwinheitzman** [comment]
Yep, I made a oopsy. Strange that it didn't fail when I ran it locally though. Should be fixed now with v6.0.6

**Comment by D0rmouse** [comment]
Works like a charm 🥇

**Comment by D0rmouse** [comment]
Since the api of the plugin is changed, shouldn't the new version be 7.0.0?

**Comment by erwinheitzman** [comment]
I like the way you think and I'll keep that in mind for upcoming versions but for now I think it's fine to keep it as it is.
